name: Other linters

on:
  pull_request:
    branches: [ master ]

jobs:
  editorconfig:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Lint other files with EditorConfig
      uses: github/super-linter/slim@v4
      env:
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_EDITORCONFIG: true
        EDITORCONFIG_FILE_NAME: .ecrc
        DEFAULT_BRANCH: master
